### ISSUE TITLE
IPython notebook version

### ISSUE THREAD

**Issue by mrocklin** [ogirardot/meta-deps#1]
I am unable to open your IPython notebook with either ipython `0.12.1` or the git development version `1.0.dev` (I get a blank notebook).  Any suggestions for how to proceed?  

Could you upload a straight Python script to avoid this issue?

**Comment by mrocklin** [comment]
Also, thanks for the data.  Nice visualization on http://ogirardot.wordpress.com/2013/01/05/state-of-the-pythonpypi-dependency-graph/

**Comment by ogirardot** [comment]
Hi Matthew, 
i'm using IPython 0.13.1, on MacOs, installing it using pip should be enough :)
i've just checked, it opened correctly, but the notebook is a bit long to open, are you sure it wasn't just loading ?

Either way you're right, i'll upload a plain old py file :).
Regards,

Olivier.

**Comment by mrocklin** [comment]
Great!  I appreciate the `.py` file.
